name: Test

on:
  push:
    branches: [master]

jobs:
  test:
    name: User Acceptance test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js v14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install npm deps
        run: npm ci
      - name: Build Svelte application
        run: npm run build
      - name: Start application
        run: npm run webserver &
      - name: Running unit test
        run: npm test
